apiVersion: v1
kind: Pod
metadata:
  name: non-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ "ALL" ]
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: workdir
          mountPath: /work
  volumes:
    - name: workdir
      emptyDir: { }

