apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ "ALL" ]
        seccompProfile:
          type: RuntimeDefault
